FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h
	HINTS
	$ENV{SDL2MIXERDIR}
    ENV SDL2DIR
    ${SDL2_DIR}
	PATH_SUFFIXES include/SDL2 include
)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(VC_LIB_PATH_SUFFIX lib/x64)
else()
  set(VC_LIB_PATH_SUFFIX lib/x86)
endif()

FIND_LIBRARY(SDL2_MIXER_LIBRARY
	NAMES SDL2_mixer
	HINTS
	$ENV{SDL2MIXERDIR}
    ENV SDL2DIR
    ${SDL2_DIR}
	PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

set(SDL2_MIXER_LIBRARIES ${SDL2_MIXER_LIBRARY})
set(SDL2_MXIER_INCLUDE_DIRS ${SDL2_MIXER_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_mixer REQUIRED_VARS SDL2_MIXER_LIBRARIES SDL2_MXIER_INCLUDE_DIRS)

mark_as_advanced(SDL2_MIXER_LIBRARY SDL2_MIXER_INCLUDE_DIR)